spring:
  application:
    name: query-ms

  datasource:
    username: query
    password: query
    url: jdbc:h2:mem:queryDb

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true

  threads:
    virtual:
      enabled: true

server:
  port: 8085

kafka:
  bootstrap:
    server: localhost:29092
  topics:
    product: product-topic
