spring:
  application:
    name: order-outbox
  main:
    banner-mode: off
    keep-alive: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    default-schema: order_outbox
  threads:
    virtual:
      enabled: true
server:
  port: 8082

