name: spring-boot-microservices

services:

  gateway:
    image: vromanyu/cqrs:gateway
    container_name: gateway
    hostname: gateway
    ports:
      - "8585:8585"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
    depends_on:
      write-ms:
        condition: service_started
    networks:
      - microservices-network

  write-ms:
    image: vromanyu/cqrs:write-ms
    container_name: write-ms
    hostname: write-ms
    depends_on:
      query-ms:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      KAFKA_BOOTSTRAP_SERVER: "kafka:9092"
    networks:
      - microservices-network

  query-ms:
    image: vromanyu/cqrs:query-ms
    container_name: query-ms
    hostname: query-ms
    depends_on:
      kafka:
        condition: service_started
      redis:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      KAFKA_BOOTSTRAP_SERVER: "kafka:9092"
      REDIS_HOST: "redis"
    networks:
      - microservices-network

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    hostname: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - microservices-network

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    command: redis-server --save 20 1
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge