quarkus.flyway.repair-at-start=true
quarkus.flyway.migrate-at-start=true
quarkus.flyway.default-schema=QUARKUS_OUTBOX

quarkus.hibernate-orm.schema-management.strategy=validate

kafka.bootstrap.servers=localhost:29092
mp.messaging.outgoing.order-out-events.connector=smallrye-kafka
mp.messaging.outgoing.order-out-events.topic=order-events
mp.messaging.outgoing.order-out-events.acks=all
mp.messaging.outgoing.order-out-events.transactional.id=order-out-events-tx-${quarkus.uuid}
