CREATE TABLE ORDER_TABLE
(
    ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ORDER_UUID   VARCHAR2(500) NOT NULL,
    ITEM_NAME    VARCHAR2(300) NOT NULL,
    PRODUCT_TYPE VARCHAR2(500) NOT NULL,
    QUANTITY     INTEGER       NOT NULL,
    PRICE        NUMBER        NOT NULL,
    CREATED_AT   TIMESTAMP     NOT NULL,
    UPDATED_AT   TIMESTAMP
);