CREATE TABLE OUTBOX_TABLE
(
    ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ORDER_ID   NUMBER                  NOT NULL,
    PAYLOAD    VARCHAR2(500)           NOT NULL,
    CREATED_AT TIMESTAMP               NOT NULL,
    PROCESSED  VARCHAR2(1) DEFAULT '1' NOT NULL,
    UPDATED_AT TIMESTAMP
);