ALTER TABLE OUTBOX_TABLE
    MODIFY (
        CREATED_AT TIMESTAMP WITH TIME ZONE,
        UPDATED_AT TIMESTAMP WITH TIME ZONE
        );

ALTER TABLE ORDER_TABLE
    MODIFY (
        CREATED_AT TIMESTAMP WITH TIME ZONE,
        UPDATED_AT TIMESTAMP WITH TIME ZONE
        );