name: build-all-workflow
on:
  workflow_dispatch:

jobs:
  choreography-gateway:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    steps:
      - name: Clone
        uses: actions/checkout@v5
      - name: JDK Setup
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'
      - name: Build/Test
        id: build
        run: mvn -B package --file choreography/choreography-gateway/pom.xml
  order-ms:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    steps:
      - name: Clone
        uses: actions/checkout@v5
      - name: JDK Setup
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'
      - name: Build/Test
        id: build
        run: mvn -B package --file choreography/pom.xml -pl order-ms -am
  payment-ms:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    steps:
      - name: Clone
        uses: actions/checkout@v5
      - name: JDK Setup
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'
      - name: Build/Test
        id: build
        run: mvn -B package --file choreography/pom.xml -pl payment-ms -am
  cqrs-gateway:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    steps:
      - name: Clone
        uses: actions/checkout@v5
      - name: JDK Setup
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'
      - name: Build/Test
        id: build
        run: mvn -B package --file cqrs/cqrs-gateway/pom.xml
  query-ms:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    steps:
      - name: Clone
        uses: actions/checkout@v5
      - name: JDK Setup
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'
      - name: Build/Test
        id: build
        run: mvn -B package --file cqrs/pom.xml -pl query-ms -am
  write-ms:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    steps:
      - name: Clone
        uses: actions/checkout@v5
      - name: JDK Setup
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'
      - name: Build/Test
        id: build
        run: mvn -B package --file cqrs/pom.xml -pl write-ms -am
